# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NestOwl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "iCarousel"

  # Pods for NestOwl

  target 'NestOwlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NestOwlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
